### ISSUE TITLE
I cannot install this onto Visual Studio 15.3.5.

### ISSUE THREAD

**Issue by Jjmboni** [Danielku15/BetterStartPage#40]
I worked all day on this.  Hopefully I didn't forget something stupid!  My steps to reproduce:
1.  Browse to https://marketplace.visualstudio.com/items?itemName=Danielku15.BetterStartPage.  Because of "reasons" my work does not allow Visual Studio to directly download extensions.  I have to download it from the website and run locally.
2.  Problem #1: The file is downloaded as BetterStartPage.zip.  That's an easy fix though, just rename to BetterStartPage.vsix.
3.  Run BetterStartPage.vsix.  Either by doubleclicking or right click and select open with "Microsoft Visual Studio Version Selector"
4.  The VSIX installer appears to start installing, but it exits with no warning.  The BetterStartPage is not installed.
5.  I tried running the VSIX installer as Administrator and it failed with the following:
4/3/2019 2:25:45 PM - System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.App.GetExtensionEngineForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.App.TryAddSkuToValidSkuList(SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
4/3/2019 2:25:45 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

My System is Windows 10 64bit, running Visual Studio 2017 15.3.5

**Comment by stijnherreman** [comment]
Are you stuck on 15.3.5 or can you update to the latest version (currently 15.9.11)? 15.3.5 was released on 2017-09-19 while the extension was last updated on 2018-08-19, so perhaps that version is no longer supported.

I couldn't reproduce the issue with downloading the extension, it was a `.vsix` file for me.

**Comment by Danielku15** [comment]
I remember also some compatibility issues with older Visual Studio 2017 versions. Microsoft was heavily moving from synchronous to task-async operations for their internals. This broke multiple times the compatibility. 
I would also strongly recommend updating Visual Studio if it is possible for you. 

But I also somehow doubt that on your error that my plugin is really the issue. If your company managed somehow to avoid installation of extensions via Market Place directly (Extension Manager in VS) I think it will also not work when you launch the VSIX installer directly. The error you are reporting is not coming from my extension, but is an issue in the VSIX installer. From the stack trace it seems that your IT might have prevented access to certain registry areas which is not expected by the installer.

**Comment by Jjmboni** [comment]
Thank you for the suggestions.  It took a couple of days but I was able to request an upgrade to 15.9.5 and once there the BetterStartPage installed with no problems.  I will close this issue.
